### ISSUE TITLE
Training Colbert on Persian datasets

### ISSUE THREAD

**Issue by poorya2021** [stanford-futuredata/ColBERT#103]
Hi again @okhat

Q1: Does Colbert support Persian?
Q2: I tried to train the model using my dataset, but in 5 minutes, the model will be trained. I use a Persian dataset. Do you think this is a reasonable amount of time to train the model?

Q3: My train file contains 18,000 queries, for each query there is a positive passage and some negative passages. Since the number of negative passages per query is more than one, I have put the negative passages of each query in a list. Is it okay to use the list in this case?
(My collection include 200k passages)

RAM: 54GB
GPU: RTX 2080 with 12 GB

**Comment by okhat** [comment]
For training, you need to prepare triples <query, positive passage ID, negative passage ID>. For each negative, add a new triple. Make sure the triples are shuffled randomly.

The default ColBERT will not work very well with Persian, since it uses bert-base-uncased (English only). You can however replace the default model with a multi-lingual BERT. This requires some extra effort, but I believe others have done it:

https://github.com/hannawong/ColXLM

https://github.com/hltcoe/ColBERT-X

**Comment by poorya2021** [comment]
Thanks so much for your Response

> For training, you need to prepare triples <query, positive passage ID, negative passage ID>. For each negative, add a new triple. Make sure the triples are shuffled randomly.
> 
> The default ColBERT will not work very well with Persian, since it uses bert-base-uncased (English only). You can however replace the default model with a multi-lingual BERT. This requires some extra effort, but I believe others have done it:
> 
> https://github.com/hannawong/ColXLM
> 
> https://github.com/hltcoe/ColBERT-X

**Comment by r1ckC139** [comment]
Hi @okhat,
Does ColBERT v1 use in-batch negative like DPR ?
Sorry for asking you here !!!
