### ISSUE TITLE
Batch Reranking is very slow

### ISSUE THREAD

**Issue by JamesDeAntonis** [stanford-futuredata/ColBERT#47]
Hello,

While batch retrieval is very fast (one pass in .3 seconds), batch reranking is very slow (one pass in roughly 10 minutes).  I think this is because the entire index is loaded in steps. I think this is unnecessary because we only care about a subset of the index.  For example, a retrieval step for me returned 2000 pids, which multiplied by 512 doc max len, means we care about 2000 * 512 = 1,024,000 vectors.  Isn't there a way to load only these vectors using a mapping?  This might cut the time down dramatically.

Curious what your thoughts are on this.

Thanks!
Jamie

EDIT: I think the `faiss.DirectMap` might be helpful here.  We know the indexes of the vectors of interest, so we can simply call `index.reconstruct(idx)` for each idx, then that will pretty quickly get us the full matrix for each doc

**Comment by okhat** [comment]
Hi James!  Batch re-ranking is intended for use when you have a very large number of queries (e.g., many thousands of queries). For those, it amortizes a lot of the costs and has a very high throughput.

I believe you're using batch mode because of limited memory. In that case, any solution that involves loading the index from memory will be slow because it has to hit the disk (I assume you're not using an SSD?). In that case, an approach that selectively loads vectors might indeed help, but only for the unusual applications where you have a *very* small number of queries to run.
