### ISSUE TITLE
Retrieve/rerank pipeline with Colbert

### ISSUE THREAD

**Issue by littlewine** [stanford-futuredata/ColBERT#67]
Hi,

Is there an easy way to make a pipeline that retrieves, then reranks and returns the run filepaths (without having to manually run both commands and pass the topk arguments) ?

Im not sure how easy it is to make a python pipeline (I saw you wrote/extended your own [argument parser](https://github.com/stanford-futuredata/ColBERT/blob/abb5b684e4cda297f3ff58b52e70d5b90270e900/colbert/utils/parser.py#L12)) 
I also started trying doing something with bash, but it means I have to parse strings etc, which is prone to errors etc. etc.

Thanks!

**Comment by okhat** [comment]
Is this for batch retrieval?

Single-query retrieval is already in one script.

**Comment by littlewine** [comment]
Yes, it has to be batch retrieval, otherwise RAM memory usage is extremely large, so impossible

**Comment by okhat** [comment]
Ah I see. You can always pass --run [name] to the retrieval step so that the output file's name is pre-defined, and then you can use the pre-defined path as input to the rerank step. You can launch both of these from the same command, as a wrapper.

Otherwise, we're actively working on a complete refactor of the codebase that has much better API (including this aspect you asked for) and very accurate yet aggressive compression. It's not perfectly stable yet, but I'm happy to invite you to the private beta if you want to try it out.
