### ISSUE TITLE
Number of epochs to train Colbert 

### ISSUE THREAD

**Issue by poorya2021** [stanford-futuredata/ColBERT#97]
Hi @okhat 
I have some questions
Q1: How do I set the number of epochs to train Colbert on a database?
Q2: What is the number of epochs to train Colbert by default?
Q3: In which file can I see the number of epoch settings for training Colbert?

Thank you

**Comment by okhat** [comment]
Thanks for asking! This is a common question.

There's no number of epochs to set. We train on triples (or, more generally, tuples) of <query, positive, negative[s]> and we train only once on each example you supply.

Because you can always sample more negatives per query--positive pair, you almost never run out of unique triples to train with, so there's no need to "repeat" examples in multiple "epochs".

That said, I recommend between 10 and 100 examples for each query-positive pair for training. For instance, if you have 10k queries, 2 positives per query, and you use batch size 32, you might want to train for anything between (10k*2*10 / 32) steps up to (10k*2*100 / 32) steps.

You can simply use the saved checkpoints for this, which are saved regularly (e.g., colbert-10000.dnn, colbert-20000.dnn, etc.) or use --maxsteps to select the stopping point.

**Comment by poorya2021** [comment]
Thanks @okhat for the good explanation

I need help using the following script to train the model
In the last line that points to the root
When I want to train the model with my own dataset (for example, PF-dataset), what should I put after the following items?
Or rather, what exactly does each of those items on the last line refer to?

```
CUDA_VISIBLE_DEVICES="0,1,2,3" \
python -m torch.distributed.launch --nproc_per_node=4 -m \
colbert.train --amp --doc_maxlen 180 --mask-punctuation --bsize 32 --accum 1 \
--triples /path/to/MSMARCO/triples.train.small.tsv \
--root /root/to/experiments/ --experiment MSMARCO-psg --similarity l2 --run msmarco.psg.l2
```

```
--root 
--experiment 
--similarity
--run 
```

Thank you

**Comment by okhat** [comment]
All of the options you listed at the bottom are optional.

You don't need to specify the similarity. Both options `l2` and `cosine` work fine. (The default is cosine.)

Root is where to save logs. Experiment is the name of your experiment. Run is the name of the current run, within the experiment. If you don't specify any of these three, some default value will be selected for you.

**Comment by maaxap** [comment]
Hi @okhat, could you clarify if pre-trained on MS MACRO v1 model is available somewhere? I’ve managed to find only v2 model in the [example notebook](https://github.com/stanford-futuredata/ColBERT/blob/new_api/docs/intro.ipynb) in `new_api` branch. Thanks in advance!

**Comment by poorya2021** [comment]
Thanks for your help
