### ISSUE TITLE
Error when indexing with ColBERTv2

### ISSUE THREAD

**Issue by vjeronymo2** [stanford-futuredata/ColBERT#99]
Hi, I'm using the new_api branch and the provided ColBERTv2 checkpoint to index a 2M dataset but the indexer doesn't seem to be able to create a ivf.pt, which I assume is related to faiss.
![Screenshot 2022-03-24 004907](https://user-images.githubusercontent.com/37119493/159842253-90c82bd2-be86-4f2b-b61c-7693cb7d546d.png)
Seems like something is getting lost. I'll debug but I just thought of dropping this here first.

**Comment by okhat** [comment]
Hmm, this is strange. Can you share more of the output? I'm primarily interested in the stage before encoding the passages, where the model is doing k-means clustering.

It basically looks like some of the centroids (clusters) are associated with none of the vectors, which is very odd!

Do you have a ton of repeated passages in your collection, by any chance? Are you able to index a 200k-passage subset (10%) of your collection just fine?

**Comment by okhat** [comment]
Ah, come to think of it, I can see how a very extreme edge case can give rise to this, if there's a lot of redundancy in the text. Basically, it looks like you get some centroids that are very close to other centroids.

I'd like to learn more about the dataset if you'd like to share more information. The easiest fix for this special case is probably to reduce the number of partitions:

https://github.com/stanford-futuredata/ColBERT/blob/378001bcc439cb3ed2d8935473c368604a7dd46e/colbert/indexing/collection_indexer.py#L75

```
self.num_partitions = int(2 ** np.floor(np.log2(16 * np.sqrt(self.num_embeddings_est))))
```

->
```
self.num_partitions = int(2 ** np.floor(np.log2(8 * np.sqrt(self.num_embeddings_est))))
```

This isn't a parameter at the moment because we've never had to edit it before, but it looks like you might need to.

**Comment by vjeronymo2** [comment]
It's an e-comerce dataset which I'm not sure I could disclose. I was able to run the indexer for the first 10k documents from the corpus with no problem.
Thanks! I'll try this suggestion and get back to you.

**Comment by vjeronymo2** [comment]
I got the same error, but with with different size `AssertionError: (torch.Size([65292]), 65536)`
[errorlog.txt](https://github.com/stanford-futuredata/ColBERT/files/8343392/errorlog.txt)

**Comment by okhat** [comment]
Could you change the line to:

```self.num_partitions = int(2 ** np.floor(np.log2(2 * np.sqrt(self.num_embeddings_est))))```

This should work. We'll edit the indexing code to handle this more gracefully in the future.

**Comment by okhat** [comment]
A nice side-effect of this change is that indexing will be faster for you.

**Comment by vjeronymo2** [comment]
Still same error:
`AssertionError: (torch.Size([16380]), 16384)`

**Comment by okhat** [comment]
Haha that is interesting. Removing the `2 *` altogether should do the trick, since the margin has become so small now

**Comment by vjeronymo2** [comment]
Now it seems to have worked! Thanks man

**Comment by vjeronymo2** [comment]
Should we close the issue?
